DompetQ2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('riwayat/', include("inOut.urls")),
    path('wishlist/', include('wishlist.urls')),
    path('jadwal/',include("jadwal.urls")),
    path('promolist/',include("promolist.urls")),
    path('',include("homePage.urls")),
    path('accounts/', include('django.contrib.auth.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inOut/urls.py
from django.urls import path
from . import views

app_name = "in_out"

urlpatterns = [
    path('', views.pemasukan, name = 'pemasukan'),
    # path('pengeluaran/', views.pengeluaran, name ='pengeluaran'),
    path('data/', views.getData, name='data')
]

inOut/models.py
from django.db import models
from django.core.validators import MaxValueValidator
from django.contrib.auth.models import User

# Create your models here.
class Saldo(models.Model):
    saldo = models.BigIntegerField(default = 0)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True) 

class Pengeluaran_Pemasukan(models.Model):
    tanggal = models.DateField(auto_now_add=True)
    jam = models.TimeField(auto_now_add=True)
    keterangan = models.CharField(default = "", max_length = 100)
    status = models.CharField(default = "",max_length = 10)
    nominal = models.IntegerField(default = 0, validators=[MaxValueValidator(9999999999)])
    saldo = models.BigIntegerField(default = 0)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True)
    inputan = models.CharField(default = "",max_length = 10)

inOut/forms.py
from django import forms
from . import models

class Rincian(forms.ModelForm):
    class Meta:
        model = models.Pengeluaran_Pemasukan
        fields = ['keterangan', 'nominal', 'inputan']

class Create_Saldo(forms.ModelForm):
    class Meta:
        model = models.Saldo
        fields = ['saldo']

inOut/views.py
from django.shortcuts import render
from . import forms
from . models import Pengeluaran_Pemasukan, Saldo
from django.shortcuts import redirect
from django.core.serializers import serialize
from django.http.response import JsonResponse


from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
# Create your views here.


def getSaldo(request):
    saldoData = Saldo.objects.filter(user = request.user.pk)
    if(len(saldoData) == 0):
        data = {'saldo':0, 'user':request.user}
        saldos = forms.Create_Saldo(data)
        if saldos.is_valid():
            saldoss = saldos.save(commit=False)
            saldoss.user = request.user
            saldoss.save()
    saldo = Saldo.objects.filter(user = request.user.pk)[0]
    return saldo

@login_required(login_url='/accounts/login')
def pemasukan(request):
    saldo = getSaldo(request)

    if request.method == 'POST':
        form = forms.Rincian(request.POST)
        if form.is_valid():
            objectRincian = form.save(commit=False)
            if objectRincian.inputan == 'in':
                objectRincian.status = 'Pemasukan'
                objectRincian.saldo = saldo.saldo + objectRincian.nominal
            else:
                objectRincian.status = 'Pengeluaran'
                objectRincian.saldo = saldo.saldo - objectRincian.nominal
            objectRincian.user = request.user
            objectRincian.save()
            saldo.saldo =  objectRincian.saldo
            saldo.save()
    else:
        form = forms.Rincian()
    context = {
        'form':form,
        'saldo':saldo
    }
    return render(request, 'pemasukan.html', context)

@login_required(login_url='/accounts/login')
def getData(request):
    item = list(Pengeluaran_Pemasukan.objects.filter(user = request.user.pk).order_by('-tanggal', '-jam'))
    data = serialize('json', item)
    return JsonResponse(data, safe=False)

inOut/templates/pemasukan.html
{% extends "base.html" %}
{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'InOut.css' %}">
{% endblock %}

{% block content %}

<div id="Title">
    <p>Masukan data pemasukan / pengeluaran kamu disini</p>
</div>

{% if saldo.saldo < 0 %}
    <div id="Warning">
        <h2>PERINGATAN!</h2>
        <p>Pengeluaran kamu telah melebihi 
            uang yang kamu miliki! Segera
            atur pengeluaranmu!
        </p>
    </div>
{% endif %}

<div class="dataForm">
    <div id="keluarMasuk">
        <a id="moveIn" class="current">Pemasukan</a>
        <a id="moveOut" class="movePage">Pengeluaran</a>
    </div>
    {% if saldo.saldo < 9999999999 %}
        <div id="formInput">
            <table>
                {% csrf_token %}
                <div id="inputFormData">
                    <label>Catatan: </label>
                    <input type="text" name="keterangan" maxlength="100" required="" id="id_keterangan">
                    <label>Nominal: </label>
                    <input type="number" name="nominal" value="0" required="" id="id_nominal">
                </div>
            </table>
        </div>
        <div id="buttonSumbit">
            <input class="submitButton" type="submit" value="Simpan">
        </div>
    {% else %}
        <div id="saldoLewat">
            <p>Saldomu melewati batas yang dapat ditampung DompetQ :(</p>
        </div>
    {% endif %}
</div>    

<div id="tabelRiwayat">
    <p id="Riwayat">Riwayat</p>
    <div id="tabelTransaksi">
        <div class="keteranganBar">
            <p class="tanggal">Tanggal</p>
            <p class="catatan">Catatan</p>
            <p class="jenis">Jenis</p>
            <p class="nominal">Nominal</p>
            <p class="saldo">Saldo</p>
        </div>
        <div class="getData"></div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="{% static 'inOut.js' %}"></script>

{% endblock %}