DompetQ2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('riwayat/', include("inOut.urls")),
    path('wishlist/', include('wishlist.urls')),
    path('jadwal/',include("jadwal.urls")),
    path('promolist/',include("promolist.urls")),
    path('',include("homePage.urls")),
    path('accounts/', include('django.contrib.auth.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inOut/urls.py
from django.urls import path
from . import views

app_name = "in_out"

urlpatterns = [
    path('', views.pemasukan, name = 'pemasukan'),
    # path('pengeluaran/', views.pengeluaran, name ='pengeluaran'),
    path('data/', views.getData, name='data')
]

wishlist/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'wishlist'

urlpatterns = [
    path('', views.wishlist_page, name = 'wishlist_page'),
    path('make-a-wish/', views.add_wishlist, name = 'add_wishlist'),
    path('delete/<id>', views.delete_wish, name = 'delete'),
    path('delete-all/', views.delete_all, name = 'all_delete'),
    path('call-data/', views.call, name = 'call_data'),
    path('get-amount/', views.get_amount, name = 'get_amount')
]

wishlist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class WishModel(models.Model):
    picture = models.ImageField(default='default.png', blank=True)
    nama = models.CharField(max_length=50)
    harga = models.IntegerField(default=0)

    def __str__(self):
        return self.nama

wishlist/forms.py
from django import forms
from . import models

class WishlistModelForm(forms.ModelForm):
    class Meta:
        model = models.WishModel
        fields = [
            'picture',
            'nama',
            'harga' 
        ]

wishlist/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from .models import WishModel
from .forms import WishlistModelForm
from django.core import serializers
from inOut.views import getSaldo
from inOut.models import Saldo
from jadwal.models import JadwalForm

# Create your views here.
@login_required()
def wishlist_page(request):
    wishes = WishModel.objects.all()
    response = {
            'wishes': wishes
    }   
    return render(request, 'wishlist_page.html', response)

@login_required
def delete_wish(request, id):
    wish = WishModel.objects.filter(id=id)[0]
    response = {
        'wish': wish
    }
    if request.method == 'POST':
        wish.delete()
        return redirect('wishlist:wishlist_page')
    return render(request, 'delete_page.html', response)

@login_required
def delete_all(request):
    wish = WishModel.objects.all()
    if request.method == 'POST':
        wish.delete()
    return redirect('wishlist:wishlist_page')

@login_required
def add_wishlist(request):
    if request.method == 'POST':
        form = WishlistModelForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.person = request.user
            obj.save()
        return redirect("wishlist:wishlist_page")
    else:
        form = WishlistModelForm()
    response = {
        'form': form
    }
    return render(request, 'add_wishlist.html', response)

def call(request):
    jadwal = JadwalForm.objects.all()
    wish = WishModel.objects.all()
    jadwal_json = serializers.serialize('python', jadwal)
    wish_json = serializers.serialize('python', wish)   
    list_data = {
        'jadwal': jadwal_json,
        'wish': wish_json
    }
    return JsonResponse(list_data, safe=False)

def get_amount(request):
    saldo = Saldo.objects.all()
    wish = WishModel.objects.all()
    saldo_json = serializers.serialize('python', saldo)
    wish_json = serializers.serialize('python', wish)
    list_data = {
        'saldo': saldo_json,
        'wish': wish_json
    }
    return JsonResponse(list_data, safe=False)

wishlist/templates/add_wishlist.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block stylesheet %} <link rel="stylesheet" href="{% static 'wishlist.css' %}"> {% endblock %}

{% block content %}
    <div class="title text-center">
        <p> Tambahkan Wishlist </p>
    </div>

    <form action="{% url 'wishlist:add_wishlist' %}" method = 'post' enctype='multipart/form-data'>
        {% csrf_token %}
        <div class="form-container">
            <div class="form-nama">
                <div class="nama">
                    <p> Nama : </p>
                </div>
                {{ form.nama }}
            </div>
    
            <div class="form-harga">
                <div class="harga">
                    <p> Harga : </p>
                </div>
                {{ form.harga }}
            </div>
    
            <div class="form-gambar">
                <div class="gambar">
                    <p> Gambar : </p>
                </div>
                {{ form.picture }}
            </div>
        </div>

        <div class="tombol-con">
            <input type="submit" value = "Tambah Wish">
    
            <div class="back-button">
                <a href="{% url 'wishlist:wishlist_page' %}">
                    Kembali
                </a>
            </div>
        </div>
        
    </form>
    

{% endblock %}

wishlist/templates/delete_page.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block stylesheet %} <link rel="stylesheet" href="{% static 'wishlist.css' %}"> {% endblock %}


{% block content %}

    <div class="title text-center">
        <p> Apakah anda yakin tidak mengincar <br> barang ini lagi ? </p>
    </div>

    <div class="wish-delete">
        <div class="img-container">
            <img src="{{ wish.picture.url }}" alt="" class="thumb">
        </div>

        <div class="desc">
            <div class="name-con">
                {{ wish.nama }}
            </div>

            <div class="harga-con">
                Rp{{ wish.harga }}
            </div>
        </div>

        
    </div>
    
    <div class="tombol-con">
        <div class="confirm-delete">
            <a href="{% url 'wishlist:wishlist_page' %}">
                Tidak, Saya Tidak Yakin
            </a>
        </div>
        
        <form action="{% url 'wishlist:delete' id=wish.id %}" method = 'post'>
            {% csrf_token %}
            <input type="submit" value = "Iya, Saya Yakin">
        </form>
    </div>


{% endblock %}

wishlist/templates/wishlist_page.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block stylesheet %} 
    <link rel="stylesheet" href="{% static 'wishlist.css' %}"> 
{% endblock %}

{% block content %}

    <div class="title text-center">
        <p> Wishlist </p>
    </div>
    
    {% for w in wishes %}
        {% empty %}

        <div class="kosong text-center">
            <p>
                Wishlistnya Masih Kosong
            </p>
        </div>
    {% endfor %}


    <div class="button-con">
        <div class="tambah-button">
            <a href="{% url 'wishlist:add_wishlist' %}">
                Tambahkan Wishlist
            </a>
        </div>

        <div class="kosong-button">
            <form action="{% url 'wishlist:all_delete' %}" method = 'post'>
                {% csrf_token %}
                <input type="submit" value = "Kosongkan  Wishlist">
            </form>
        </div>
    </div>


    <div class="wishes">
        {% for wish in wishes %}
                <div class="wish">
                    <div class="img-container">
                        <img src="{{ wish.picture.url }}" alt="" class="thumb">
                    </div>
        
                    <div class="desc">
                        <div class="name-con">
                            <p>
                                {{ wish.nama }}
                            </p>
                        </div>
        
                        <div class="harga-con">
                            <p>
                                Rp{{ wish.harga }}
                            </p>
                        </div>
                    </div>
                    
                    <div class="button-con">
                        <form action="{% url 'wishlist:delete' id=wish.id %}">
                            {% csrf_token %}
                            <input type="submit" value = "Hapus Barang">
                        </form>
                    </div>

                    <input type="submit" value="Check" class = 'check-button'>
                </div>
        {% endfor %}

        
    </div>

    <script
    src="https://code.jquery.com/jquery-3.4.1.js"
    integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
    crossorigin="anonymous"></script>
    <script src="{% static 'wishlist.js' %}"></script>
{% endblock %}