DompetQ2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('riwayat/', include("inOut.urls")),
    path('wishlist/', include('wishlist.urls')),
    path('jadwal/',include("jadwal.urls")),
    path('promolist/',include("promolist.urls")),
    path('',include("homePage.urls")),
    path('accounts/', include('django.contrib.auth.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inOut/urls.py
from django.urls import path
from . import views

app_name = "in_out"

urlpatterns = [
    path('', views.pemasukan, name = 'pemasukan'),
    # path('pengeluaran/', views.pengeluaran, name ='pengeluaran'),
    path('data/', views.getData, name='data')
]

promolist/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "promolist"

urlpatterns = [
    path('', views.promoisi, name = 'promolist'),
    path('create/', views.promoisi_create, name= 'create'),
    path('delete/', views.promoisi_delete, name ='delete'),
    path('getData/',views.getData,name='getData'),
]

promolist/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
# Create your models here.
class isipromo(models.Model):

    KATEGORI_CHOICES = (
        ('Makanan','Makanan'),
        ('Transportasi','Transportasi'),
        ('Rekreasi','Rekreasi'),
        ('Lain-Lain','Lain-Lain'),
    )
    Kategori = models.CharField(max_length=100, choices = KATEGORI_CHOICES)
    Nama_Promo = models.CharField(max_length=30)
    Kode_Promo = models.CharField(max_length=30)
    Mulai_Promo = models.DateTimeField(default=datetime.now)
    Promo_Sampai = models.DateTimeField( default=datetime.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True)
  

promolist/forms.py
from django import forms
from .models import isipromo

class PromoForm(forms.ModelForm):
    class Meta:
        model = isipromo
        fields = ['Kategori', 'Nama_Promo', 'Kode_Promo', 'Mulai_Promo', 'Promo_Sampai']

promolist/views.py
from django.shortcuts import render, redirect
from . import forms
from .models import isipromo
from django.core import serializers
from django.http import HttpResponse
from django.http import JsonResponse

from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
# Create your views here.

# Create your views here.

@login_required(login_url='/accounts/login')
def promoisi(request):
    promos = isipromo.objects.filter(user = request.user.pk).order_by()
    return render(request, 'promolist.html', {'promos': promos})

@login_required(login_url='/accounts/login')
def promoisi_create(request):
    if request.method == 'POST':
        form = forms.PromoForm(request.POST)
        if form.is_valid():
            data = form.save(commit = False)
            data.user = request.user
            data.save()
            
            return redirect('promolist:promolist')

    else:
        form = forms.PromoForm()
    return render(request, 'promo_create.html', {'form': form})

@login_required(login_url='/accounts/login')
def promoisi_delete(request):
    isipromo.objects.filter(user = request.user.pk).delete()
    return render(request, "promolist.html")

@login_required(login_url='/accounts/login')
def getData(request):
    Schedule = isipromo.objects.filter(user = request.user.pk)
    schedule_list = serializers.serialize('python', Schedule)
    return JsonResponse(schedule_list, safe=False)
   

promolist/templates/promo_create.html
{% extends "base.html" %}
{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'promolist.css' %}">
{% endblock %}

{% block content %}
<div class="pageisipromo">
    <div class="container-fluid">
    <div class = "title">
        <p class="title-text text-center"><strong>PROMO</strong></p>
    </div>

    <div class="margin-small form-design">
        <form class="css" action="{% url 'promolist:create' %}" method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-sm-1"></div>
                <div class="form-group col-sm-10">
                    {% for fields in form %}
                        {{ fields.label_tag }}
                        <br>
                        {{ fields }}
                        <br><br>
                    {% endfor %}
                </div>
            </div>
            <div class="form-row" id="buttonbawah">
                <div class="col-sm-1"></div>
                <input type="submit" type="button" class="btn btn-warning btn-style" value="tambahkan promo" id="tambah"></button>
                <div class="col-sm-7"></div>
                <a href="{% url 'promolist:promolist' %}"><button type="button" class="btn btn-warning btn-style">kembali</button></a>
        </form>
    </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="{% static 'promolist.js' %}"></script>


{% endblock %}

promolist/templates/promolist.html
{% extends "base.html" %}
{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'promolist.css' %}">
{% endblock %}

{% block content %}
<div class="promopage">
    <div class="container-fluid">
            <div class = "title">
                <p class="title-text text-center"><strong>PROMO</strong></p>
            </div>
        
        <div class = "row justify-content-center" id="buttonpagepromo">
            <div class = 'form-group'>
                <a href="{% url 'promolist:create' %}" class="buttontambah"><button type="button" class="btn btn-warning btn-style" id ="button1">tambah promo</button></a>
                <a href="{% url 'promolist:delete' %}" class="buttonhapus"><button type="button" class="btn btn-warning btn-style" id ="button2">hapus semua</button></a>
            </div>
        </div> 

        <div id="promo">
            <div class="row justify-content-center" id='to-app'>
                <!-- {% for items in promos %}
                    <div class="col-md-3">
                            <div class="card" style="width: 18rem;">
                                <div class="card-body">
                                <h5 class="card-title">{{items.Kategori}}</h5>
                                <h5 class="card-title">{{items.Nama_Promo}}</h5>
                                <p class="card-text">{{items.Kode_Promo}}</p>
                                <p class="card-text">{{items.Mulai_Promo.date }}</p>
                                <p class="card-text">{{items.Promo_Sampai.date }}</p>
                                </div>
                            </div>
                        </div>
                {% endfor %} -->
                </div>
            </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="{% static 'promolist.js' %}"></script>

{% endblock %}