DompetQ2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('riwayat/', include("inOut.urls")),
    path('wishlist/', include('wishlist.urls')),
    path('jadwal/',include("jadwal.urls")),
    path('promolist/',include("promolist.urls")),
    path('',include("homePage.urls")),
    path('accounts/', include('django.contrib.auth.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homePage/urls.py
from django.urls import path
from . import views

app_name = "home_page"

urlpatterns = [
    path('', views.home_page, name = 'home')
]

inOut/urls.py
from django.urls import path
from . import views

app_name = "in_out"

urlpatterns = [
    path('', views.pemasukan, name = 'pemasukan'),
    # path('pengeluaran/', views.pengeluaran, name ='pengeluaran'),
    path('data/', views.getData, name='data')
]

jadwal/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'jadwalIni'

urlpatterns = [
    path('', views.SchedulePost, name='SchedulePost'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('getData/',views.getData,name='getData'),
]

promolist/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "promolist"

urlpatterns = [
    path('', views.promoisi, name = 'promolist'),
    path('create/', views.promoisi_create, name= 'create'),
    path('delete/', views.promoisi_delete, name ='delete'),
    path('getData/',views.getData,name='getData'),
]

wishlist/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'wishlist'

urlpatterns = [
    path('', views.wishlist_page, name = 'wishlist_page'),
    path('make-a-wish/', views.add_wishlist, name = 'add_wishlist'),
    path('delete/<id>', views.delete_wish, name = 'delete'),
    path('delete-all/', views.delete_all, name = 'all_delete'),
    path('call-data/', views.call, name = 'call_data'),
    path('get-amount/', views.get_amount, name = 'get_amount')
]

templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset = "UTF-8">
        <meta name= "viewport" content="width=device-width, initial-scale=1.0">
        <title>DompetQ</title>
        <link rel="stylesheet" href="{% static 'bootstrap-4.3.1-dist/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'DompetQ.css' %}">
        {% block stylesheet %}
        {% endblock %}

    </head>

    <body>
        <nav class="navbar fixed-top navbar-expand-xl navbar-light">
            <a class="navbar-brand" href="{% url 'home_page:home' %}">DompetQ</a>
            <button class="navbar-toggler mt-2" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'in_out:pemasukan' %}" href="">In/Out</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'jadwalIni:SchedulePost' %}">Jadwal</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'wishlist:wishlist_page' %}">Wishlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'promolist:promolist' %}">PromoList</a>
                </li>
                {% if saldo != None %}
                    <li class="nav-item" id="navSaldo">
                            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item" id="navLogin">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                {% endif %}
                </ul>
            </div>
        </nav> 

        {% block content %}
        {% endblock %}
        
        </div>
        <footer id="footer">
            <div id="socmed">
                <a id="ig" href="https://www.instagram.com/dompetq" target="_blank">
                    <img src="{% static 'instagram2.svg' %}" alt="">
                </a>
                <a id="twitter" href="https://www.twitter.com/QDompet" target="_blank">
                    <img src="{% static 'twitter.svg' %}" alt="">
                </a>
            </div>
       </footer>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script src='https://kit.fontawesome.com/a076d05399.js'></script>
        <script src="{% static 'DompetQ.js' %}"></script>
        
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
   
    </body>
    {% block javascript %}
    {% endblock javascript%}
</html>